# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

# install: pip install tox
install: pip install -r requirements.txt

script: tox

# notifications:
  # email: false
