# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geogame', '0002_scenario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
